# Generated by Django 3.2.5 on 2021-07-16 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20210716_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CumpomDesconto',
            new_name='CupomDesconto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.cupomdesconto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 14, 59, 49, 29918)),
        ),
    ]
